#include "codegen/x86_backend.hpp"
#include <cstdio>
#include <cstring>
#include <cassert>
#include <cctype>
#include <cmath>

namespace TCC_Pro {

X86LinuxBackend::X86LinuxBackend(SymbolTable& syms, TypeContext& types)
    : syms_(syms), types_(types) {}

void X86LinuxBackend::emit(const std::string& s) { out_ << s; }
void X86LinuxBackend::emit(const char* s) { out_ << s; }
void X86LinuxBackend::emitLine(const std::string& s) { out_ << s; if (s.back() != '\n') out_ << "\n"; }
void X86LinuxBackend::beginProgram() {
    org_ = 0; floatNum_ = 0; tempNum_ = 0;
    emitLine("# Code auto-generated by TCC_Pro\n");
}
void X86LinuxBackend::endProgram() {}
std::string X86LinuxBackend::getOutput() { return out_.str(); }

void X86LinuxBackend::segment(int seg) {
    if (seg == DATA) emitLine(".data\n");
    else if (seg == CODE) emitLine(".text\n");
}

void X86LinuxBackend::import(Symbol* p) { (void)p; }
void X86LinuxBackend::export_(Symbol* p) {
    char buf[256];
    snprintf(buf, sizeof(buf), ".globl\t%s\n", getAccessName(p));
    emitLine(buf);
    emitLine("");
}

const char* X86LinuxBackend::getAccessName(Symbol* p) {
    if (p->aname) return p->aname;

    switch (p->kind) {
    case SK_Constant: {
        char* buf = new char[64];
        snprintf(buf, 64, "$%s", p->name);
        p->aname = buf; break;
    }
    case SK_String: case SK_Label: {
        char* buf = new char[64];
        snprintf(buf, 64, ".%s", p->name);
        p->aname = buf; break;
    }
    case SK_Variable: case SK_Temp: {
        auto* v = static_cast<VariableSymbol*>(p);
        if (p->kind == SK_Function) {
            p->aname = p->name;
        } else if (p->sclass == 3 && p->level > 0) {
            char* buf = new char[64];
            snprintf(buf, 64, "%s.%d", p->name, tempNum_++);
            p->aname = buf;
        } else if (p->level > 0 || p->kind == SK_Temp) {
            // Assign unique stack offset
            int offset;
            auto it = stackSlots_.find(p);
            if (it != stackSlots_.end()) {
                offset = it->second;
            } else {
                offset = stackOffset_;
                stackOffset_ -= 4;
                stackSlots_[p] = offset;
            }
            v->offset = offset;
            char* buf = new char[64];
            snprintf(buf, 64, "%d(%%ebp)", offset);
            p->aname = buf;
        } else {
            p->aname = p->name;
        }
        break;
    }
    case SK_Function:
        p->aname = p->name; break;
    case SK_Offset: {
        auto* base = p->link;
        auto* v = static_cast<VariableSymbol*>(p);
        int n = v->offset;
        if (base->level == 0 || base->sclass == 3) {
            char* buf = new char[128];
            snprintf(buf, 128, "%s%s%d", getAccessName(base), n >= 0 ? "+" : "", n);
            p->aname = buf;
        } else {
            n += static_cast<VariableSymbol*>(base)->offset;
            char* buf = new char[64];
            snprintf(buf, 64, "%d(%%ebp)", n);
            p->aname = buf;
        }
        break;
    }
    default: p->aname = "???"; break;
    }
    return p->aname;
}

void X86LinuxBackend::defineGlobal(Symbol* p) {
    if (p->sclass != 3) export_(p);
    char buf[256];
    snprintf(buf, sizeof(buf), "%s:", getAccessName(p));
    emitLine(buf);
}

void X86LinuxBackend::defineCommData(Symbol* p) {
    getAccessName(p);
    char buf[256];
    if (p->sclass == 3)
        snprintf(buf, sizeof(buf), ".lcomm\t%s,%d\n", p->aname, p->ty->size);
    else
        snprintf(buf, sizeof(buf), ".comm\t%s,%d\n", p->aname, p->ty->size);
    emit(buf);
}

struct StrBuf { char* chs; int len; };

void X86LinuxBackend::defineString(void* str, int) {
    auto* s = static_cast<StrBuf*>(str);
    int size = s->len + 1;  // include null terminator
    if (s->chs[size] == 0) { emit("\t.string\t\""); size--; }
    else emit("\t.ascii\t\"");
    for (int i = 0; i < size; i++) {
        if (!isprint(s->chs[i])) {
            char buf[16];
            snprintf(buf, sizeof(buf), "\\%03o", (unsigned char)s->chs[i]);
            emit(buf);
        } else {
            if (s->chs[i] == '"') emit("\\\"");
            else if (s->chs[i] == '\\') emit("\\\\");
            else { char b[2] = {s->chs[i], 0}; emit(b); }
        }
    }
    emitLine("\"");
}

void X86LinuxBackend::defineFloatConstant(Symbol* p) {
    char buf[64];
    snprintf(buf, sizeof(buf), ".flt%d", floatNum_++);
    p->aname = strdup(buf);
    emit(p->aname);
    emitLine(":");
    defineValue(p->ty, p->val);
}

void X86LinuxBackend::defineAddress(Symbol* p) {
    char buf[256];
    snprintf(buf, sizeof(buf), "\t.long\t%s\n", getAccessName(p));
    emit(buf);
}

void X86LinuxBackend::defineValue(Type* ty, Value val) {
    auto tc = types_.typeCode(ty);
    char buf[128];
    switch (tc) {
    case I1: case U1: snprintf(buf, sizeof(buf), "\t.byte\t%d\n", val.i[0] & 0xff); break;
    case I2: case U2: snprintf(buf, sizeof(buf), "\t.word\t%d\n", val.i[0] & 0xffff); break;
    case I4: case U4: snprintf(buf, sizeof(buf), "\t.long\t%d\n", val.i[0]); break;
    case F4: snprintf(buf, sizeof(buf), "\t.long\t%d\n", *(unsigned*)&val.f); break;
    case F8: {
        emit("\t.long\t");
        auto* p = (unsigned*)&val.d;
        char tmp[128];
        snprintf(tmp, sizeof(tmp), "%d\n\t.long\t%d\n", p[0], p[1]);
        emit(tmp);
        return;
    }
    default: return;
    }
    emit(buf);
}

void X86LinuxBackend::space(int size) {
    char buf[64];
    snprintf(buf, sizeof(buf), "\t.space\t%d\n", size);
    emit(buf);
}

void X86LinuxBackend::defineLabel(Symbol* p) {
    char buf[128];
    snprintf(buf, sizeof(buf), "%s:\n", getAccessName(p));
    emit(buf);
}

void X86LinuxBackend::setupRegisters() {}
void X86LinuxBackend::clearRegs() { usedRegs_ = 0; }
Symbol* X86LinuxBackend::getReg() { return regs_[0].reg; }
Symbol* X86LinuxBackend::getByteReg() { return regs_[0].byteReg; }
Symbol* X86LinuxBackend::getWordReg() { return regs_[0].wordReg; }
void X86LinuxBackend::storeVar(Symbol*, Symbol*) {}
void X86LinuxBackend::spillReg(Symbol*) {}

void X86LinuxBackend::putASMCode(int code, Symbol* opds[]) {
    (void)code; (void)opds;
    // Will be called by emitIR
}

void X86LinuxBackend::emitPrologue() {
    emitLine("\tpushl %ebp");
    emitLine("\tpushl %ebx");
    emitLine("\tpushl %esi");
    emitLine("\tpushl %edi");
    emitLine("\tmovl %esp, %ebp");
    emitLine("\tsubl $256, %esp");  // Reserve 256 bytes for locals
}

void X86LinuxBackend::emitEpilogue() {
    emitLine("\tmovl %ebp, %esp");
    emitLine("\tpopl %edi");
    emitLine("\tpopl %esi");
    emitLine("\tpopl %ebx");
    emitLine("\tpopl %ebp");
    emitLine("\tret");
}

void X86LinuxBackend::emitFunction(Symbol* func) {
    auto* fsym = static_cast<FunctionSymbol*>(func);
    stackSlots_.clear();
    stackOffset_ = -4;
    export_(func);
    emitLine(std::string(getAccessName(func)) + ":");
    emitPrologue();
    emitFunctionBody(fsym);
    emitEpilogue();
    emitLine("");
}

void X86LinuxBackend::emitFunctionBody(FunctionSymbol* fsym) {
    BBlock* bb = reinterpret_cast<BBlock*>(fsym->entryBB);
    while (bb) {
        // Create and emit label for blocks that have incoming edges
        if (bb->npred > 0 || bb != reinterpret_cast<BBlock*>(fsym->entryBB)) {
            if (!bb->sym) bb->sym = syms_.createLabel();
        }
        if (bb->sym) {
            emitLine(std::string(getAccessName(bb->sym)) + ":");
        }
        auto* inst = bb->insth.next;
        while (inst != &bb->insth) {
            emitIR(inst);
            inst = inst->next;
        }
        bb = bb->next;
    }
}

void X86LinuxBackend::emitIR(IRInst* inst) {
    char buf[256];
    switch (inst->opcode) {
    case OpCode::ADDR: {
        auto* src = inst->opds[1];
        if (src->kind == SK_String) {
            snprintf(buf, sizeof(buf), "\tleal %s, %%eax", getAccessName(src));
            emitLine(buf);
            snprintf(buf, sizeof(buf), "\tmovl %%eax, %s", getAccessName(inst->opds[0]));
        } else {
            snprintf(buf, sizeof(buf), "\tleal %s, %s",
                getAccessName(src), getAccessName(inst->opds[0]));
        }
        break;
    }
    case OpCode::MOV: {
        auto* dst = inst->opds[0];
        auto* src = inst->opds[1];
        if (src->kind == SK_Constant) {
            // Immediate to register/stack
            snprintf(buf, sizeof(buf), "\tmovl $%d, %s", src->val.i[0], getAccessName(dst));
        } else if (src->kind == SK_String) {
            // String address (leal)
            snprintf(buf, sizeof(buf), "\tleal %s, %%eax", getAccessName(src));
            emitLine(buf);
            snprintf(buf, sizeof(buf), "\tmovl %%eax, %s", getAccessName(dst));
        } else {
            snprintf(buf, sizeof(buf), "\tmovl %s, %%eax", getAccessName(src));
            emitLine(buf);
            snprintf(buf, sizeof(buf), "\tmovl %%eax, %s", getAccessName(dst));
        }
        break;
    }
    case OpCode::ADD:
        snprintf(buf, sizeof(buf), "\tmovl %s, %%eax", getAccessName(inst->opds[1]));
        emitLine(buf);
        snprintf(buf, sizeof(buf), "\taddl %s, %%eax", getAccessName(inst->opds[2]));
        emitLine(buf);
        snprintf(buf, sizeof(buf), "\tmovl %%eax, %s", getAccessName(inst->opds[0]));
        break;
    case OpCode::SUB:
        snprintf(buf, sizeof(buf), "\tmovl %s, %%eax", getAccessName(inst->opds[1]));
        emitLine(buf);
        snprintf(buf, sizeof(buf), "\tsubl %s, %%eax", getAccessName(inst->opds[2]));
        emitLine(buf);
        snprintf(buf, sizeof(buf), "\tmovl %%eax, %s", getAccessName(inst->opds[0]));
        break;
    case OpCode::MUL:
        snprintf(buf, sizeof(buf), "\tmovl %s, %%eax", getAccessName(inst->opds[1]));
        emitLine(buf);
        snprintf(buf, sizeof(buf), "\timull %s, %%eax", getAccessName(inst->opds[2]));
        emitLine(buf);
        snprintf(buf, sizeof(buf), "\tmovl %%eax, %s", getAccessName(inst->opds[0]));
        break;
    case OpCode::DIV:
        emitLine("\tmovl $0, %edx");
        snprintf(buf, sizeof(buf), "\tmovl %s, %%eax", getAccessName(inst->opds[1]));
        emitLine(buf);
        snprintf(buf, sizeof(buf), "\tdivl %s", getAccessName(inst->opds[2]));
        emitLine(buf);
        snprintf(buf, sizeof(buf), "\tmovl %%eax, %s", getAccessName(inst->opds[0]));
        break;
    case OpCode::MOD:
        emitLine("\tmovl $0, %edx");
        snprintf(buf, sizeof(buf), "\tmovl %s, %%eax", getAccessName(inst->opds[1]));
        emitLine(buf);
        snprintf(buf, sizeof(buf), "\tdivl %s", getAccessName(inst->opds[2]));
        emitLine(buf);
        snprintf(buf, sizeof(buf), "\tmovl %%edx, %s", getAccessName(inst->opds[0]));
        break;
    case OpCode::BOR:
        snprintf(buf, sizeof(buf), "\tmovl %s, %%eax", getAccessName(inst->opds[1]));
        emitLine(buf);
        snprintf(buf, sizeof(buf), "\torl %s, %%eax", getAccessName(inst->opds[2]));
        emitLine(buf);
        snprintf(buf, sizeof(buf), "\tmovl %%eax, %s", getAccessName(inst->opds[0]));
        break;
    case OpCode::BAND:
        snprintf(buf, sizeof(buf), "\tmovl %s, %%eax", getAccessName(inst->opds[1]));
        emitLine(buf);
        snprintf(buf, sizeof(buf), "\tandl %s, %%eax", getAccessName(inst->opds[2]));
        emitLine(buf);
        snprintf(buf, sizeof(buf), "\tmovl %%eax, %s", getAccessName(inst->opds[0]));
        break;
    case OpCode::BXOR:
        snprintf(buf, sizeof(buf), "\tmovl %s, %%eax", getAccessName(inst->opds[1]));
        emitLine(buf);
        snprintf(buf, sizeof(buf), "\txorl %s, %%eax", getAccessName(inst->opds[2]));
        emitLine(buf);
        snprintf(buf, sizeof(buf), "\tmovl %%eax, %s", getAccessName(inst->opds[0]));
        break;
    case OpCode::NEG:
        snprintf(buf, sizeof(buf), "\tmovl %s, %%eax", getAccessName(inst->opds[1]));
        emitLine(buf);
        emitLine("\tnegl %eax");
        snprintf(buf, sizeof(buf), "\tmovl %%eax, %s", getAccessName(inst->opds[0]));
        return;
    case OpCode::CALL: {
        // Push arguments in reverse order (args stored in opds[2] as vector ptr)
        auto* faddr = inst->opds[1];
        const char* fname = faddr->name ? faddr->name : getAccessName(faddr);

        // Emit arguments as pushes
        if (inst->opds[2]) {
            auto* args = reinterpret_cast<std::vector<Symbol*>*>(inst->opds[2]);
            for (int i = static_cast<int>(args->size()) - 1; i >= 0; i--) {
                auto* arg = (*args)[i];
                if (arg->kind == SK_Constant) {
                    snprintf(buf, sizeof(buf), "\tpushl $%d", arg->val.i[0]);
                } else if (arg->kind == SK_String) {
                    snprintf(buf, sizeof(buf), "\tleal %s, %%eax", getAccessName(arg));
                    emitLine(buf);
                    emitLine("\tpushl %eax");
                    continue;
                } else {
                    snprintf(buf, sizeof(buf), "\tpushl %s", getAccessName(arg));
                }
                emitLine(buf);
            }
        }

        snprintf(buf, sizeof(buf), "\tcall %s", fname);
        emitLine(buf);

        // Clean up stack: addl $n, %esp where n = 4 * num_args
        if (inst->opds[2]) {
            auto* args = reinterpret_cast<std::vector<Symbol*>*>(inst->opds[2]);
            int stackSize = static_cast<int>(args->size()) * 4;
            if (stackSize > 0) {
                snprintf(buf, sizeof(buf), "\taddl $%d, %%esp", stackSize);
                emitLine(buf);
            }
        }

        if (inst->opds[0]) {
            snprintf(buf, sizeof(buf), "\tmovl %%eax, %s", getAccessName(inst->opds[0]));
            emitLine(buf);
        }
        return;
    }
    case OpCode::RET:
        snprintf(buf, sizeof(buf), "\tmovl %s, %%eax", getAccessName(inst->opds[0]));
        break;
    case OpCode::JMP: {
        auto* target = reinterpret_cast<BBlock*>(inst->opds[0]);
        if (!target->sym) {
            target->sym = syms_.createLabel();
        }
        snprintf(buf, sizeof(buf), "\tjmp %s", getAccessName(target->sym));
        break;
    }
    case OpCode::JE: case OpCode::JNE:
    case OpCode::JG: case OpCode::JL:
    case OpCode::JGE: case OpCode::JLE:
    case OpCode::JZ: case OpCode::JNZ: {
        auto* target = reinterpret_cast<BBlock*>(inst->opds[0]);
        if (!target->sym) target->sym = syms_.createLabel();
        auto* s1 = inst->opds[1];
        auto* s2 = inst->opds[2];
        if (s2) {
            // Load one operand into register for cmp
            snprintf(buf, sizeof(buf), "\tmovl %s, %%eax", getAccessName(s2));
            emitLine(buf);
            snprintf(buf, sizeof(buf), "\tcmpl %%eax, %s", getAccessName(s1));
            emitLine(buf);
        } else {
            snprintf(buf, sizeof(buf), "\tcmpl $0, %s", getAccessName(s1));
            emitLine(buf);
        }
        const char* jcc;
        switch (inst->opcode) {
        case OpCode::JE: jcc = "je"; break;
        case OpCode::JNE: case OpCode::JNZ: jcc = "jne"; break;
        case OpCode::JG: jcc = "jg"; break;
        case OpCode::JL: jcc = "jl"; break;
        case OpCode::JGE: jcc = "jge"; break;
        case OpCode::JLE: jcc = "jle"; break;
        case OpCode::JZ: jcc = "je"; break;
        default: jcc = "je"; break;
        }
        snprintf(buf, sizeof(buf), "\t%s %s", jcc, getAccessName(target->sym));
        break;
    }
    default:
        snprintf(buf, sizeof(buf), "\t# opcode %d", static_cast<int>(inst->opcode));
        break;
    }
    emitLine(buf);
}

void X86LinuxBackend::emitInst(int opcode, Symbol* opds[]) {
    (void)opcode; (void)opds;
}

} // namespace TCC_Pro
